package com.domain;

import java.math.BigDecimal;
import java.util.Date;

public class SdicIndexData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.MEASURE_PERIOD
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private String measurePeriod;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.MEASURE_TYPE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private String measureType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.COMPANY_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private BigDecimal companyId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.INDEX_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private BigDecimal indexId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.POWER_UNIT_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private BigDecimal powerUnitId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.NUM_VALUE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private Float numValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DATA.LAST_UPDATE_DATE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.MEASURE_PERIOD
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.MEASURE_PERIOD
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public String getMeasurePeriod() {
        return measurePeriod;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.MEASURE_PERIOD
     *
     * @param measurePeriod the value for IFSAPP.SDIC_INDEX_DATA.MEASURE_PERIOD
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setMeasurePeriod(String measurePeriod) {
        this.measurePeriod = measurePeriod;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.MEASURE_TYPE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.MEASURE_TYPE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public String getMeasureType() {
        return measureType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.MEASURE_TYPE
     *
     * @param measureType the value for IFSAPP.SDIC_INDEX_DATA.MEASURE_TYPE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setMeasureType(String measureType) {
        this.measureType = measureType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.COMPANY_ID
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.COMPANY_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public BigDecimal getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.COMPANY_ID
     *
     * @param companyId the value for IFSAPP.SDIC_INDEX_DATA.COMPANY_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setCompanyId(BigDecimal companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.INDEX_ID
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.INDEX_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public BigDecimal getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.INDEX_ID
     *
     * @param indexId the value for IFSAPP.SDIC_INDEX_DATA.INDEX_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setIndexId(BigDecimal indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.POWER_UNIT_ID
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.POWER_UNIT_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public BigDecimal getPowerUnitId() {
        return powerUnitId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.POWER_UNIT_ID
     *
     * @param powerUnitId the value for IFSAPP.SDIC_INDEX_DATA.POWER_UNIT_ID
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setPowerUnitId(BigDecimal powerUnitId) {
        this.powerUnitId = powerUnitId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.NUM_VALUE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.NUM_VALUE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public Float getNumValue() {
        return numValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.NUM_VALUE
     *
     * @param numValue the value for IFSAPP.SDIC_INDEX_DATA.NUM_VALUE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setNumValue(Float numValue) {
        this.numValue = numValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DATA.LAST_UPDATE_DATE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DATA.LAST_UPDATE_DATE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DATA.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IFSAPP.SDIC_INDEX_DATA.LAST_UPDATE_DATE
     *
     * @abatorgenerated Sat Dec 10 12:07:21 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}