package com.domain;

import java.util.Date;

public class SdicSisData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_ID
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    private String measurePointId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_DATA.MEASURE_TIME
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    private String measureTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_VALUE
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    private Short measurePointValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_DATA.LAST_UPDATE_DATE
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_ID
     *
     * @return the value of IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_ID
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public String getMeasurePointId() {
        return measurePointId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_ID
     *
     * @param measurePointId the value for IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_ID
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public void setMeasurePointId(String measurePointId) {
        this.measurePointId = measurePointId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_DATA.MEASURE_TIME
     *
     * @return the value of IFSAPP.SDIC_SIS_DATA.MEASURE_TIME
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public String getMeasureTime() {
        return measureTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_DATA.MEASURE_TIME
     *
     * @param measureTime the value for IFSAPP.SDIC_SIS_DATA.MEASURE_TIME
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public void setMeasureTime(String measureTime) {
        this.measureTime = measureTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_VALUE
     *
     * @return the value of IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_VALUE
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public Short getMeasurePointValue() {
        return measurePointValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_VALUE
     *
     * @param measurePointValue the value for IFSAPP.SDIC_SIS_DATA.MEASURE_POINT_VALUE
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public void setMeasurePointValue(Short measurePointValue) {
        this.measurePointValue = measurePointValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_DATA.LAST_UPDATE_DATE
     *
     * @return the value of IFSAPP.SDIC_SIS_DATA.LAST_UPDATE_DATE
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_DATA.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for IFSAPP.SDIC_SIS_DATA.LAST_UPDATE_DATE
     *
     * @abatorgenerated Sat Dec 10 12:16:39 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}