package com.domain;

import java.math.BigDecimal;

public class SdicSisIndexMapping {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    private String measurePointId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_NAME
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    private String measurePointName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.INDEX_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    private BigDecimal indexId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.POWER_UNIT_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    private BigDecimal powerUnitId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_ID
     *
     * @return the value of IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public String getMeasurePointId() {
        return measurePointId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_ID
     *
     * @param measurePointId the value for IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public void setMeasurePointId(String measurePointId) {
        this.measurePointId = measurePointId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.ID
     *
     * @return the value of IFSAPP.SDIC_SIS_INDEX_MAPPING.ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.ID
     *
     * @param id the value for IFSAPP.SDIC_SIS_INDEX_MAPPING.ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_NAME
     *
     * @return the value of IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_NAME
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public String getMeasurePointName() {
        return measurePointName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_NAME
     *
     * @param measurePointName the value for IFSAPP.SDIC_SIS_INDEX_MAPPING.MEASURE_POINT_NAME
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public void setMeasurePointName(String measurePointName) {
        this.measurePointName = measurePointName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.INDEX_ID
     *
     * @return the value of IFSAPP.SDIC_SIS_INDEX_MAPPING.INDEX_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public BigDecimal getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.INDEX_ID
     *
     * @param indexId the value for IFSAPP.SDIC_SIS_INDEX_MAPPING.INDEX_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public void setIndexId(BigDecimal indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.POWER_UNIT_ID
     *
     * @return the value of IFSAPP.SDIC_SIS_INDEX_MAPPING.POWER_UNIT_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public BigDecimal getPowerUnitId() {
        return powerUnitId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_SIS_INDEX_MAPPING.POWER_UNIT_ID
     *
     * @param powerUnitId the value for IFSAPP.SDIC_SIS_INDEX_MAPPING.POWER_UNIT_ID
     *
     * @abatorgenerated Sat Dec 10 12:17:11 CST 2016
     */
    public void setPowerUnitId(BigDecimal powerUnitId) {
        this.powerUnitId = powerUnitId;
    }
}