package com.domain;

import java.math.BigDecimal;

public class SdicIndexDimension {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_ID
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    private BigDecimal indexId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_NAME
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    private String indexName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    private String indexType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DIMENSION.CAL_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    private String calType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DIMENSION.MEASURE_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    private String measureType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column IFSAPP.SDIC_INDEX_DIMENSION.IOC_IMAGE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    private String iocImage;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_ID
     *
     * @return the value of IFSAPP.SDIC_INDEX_DIMENSION.INDEX_ID
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    
    private String unitName;
    
    
    public BigDecimal getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_ID
     *
     * @param indexId the value for IFSAPP.SDIC_INDEX_DIMENSION.INDEX_ID
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public void setIndexId(BigDecimal indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_NAME
     *
     * @return the value of IFSAPP.SDIC_INDEX_DIMENSION.INDEX_NAME
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_NAME
     *
     * @param indexName the value for IFSAPP.SDIC_INDEX_DIMENSION.INDEX_NAME
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_TYPE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DIMENSION.INDEX_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public String getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.INDEX_TYPE
     *
     * @param indexType the value for IFSAPP.SDIC_INDEX_DIMENSION.INDEX_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public void setIndexType(String indexType) {
        this.indexType = indexType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.CAL_TYPE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DIMENSION.CAL_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public String getCalType() {
        return calType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.CAL_TYPE
     *
     * @param calType the value for IFSAPP.SDIC_INDEX_DIMENSION.CAL_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public void setCalType(String calType) {
        this.calType = calType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.MEASURE_TYPE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DIMENSION.MEASURE_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public String getMeasureType() {
        return measureType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.MEASURE_TYPE
     *
     * @param measureType the value for IFSAPP.SDIC_INDEX_DIMENSION.MEASURE_TYPE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public void setMeasureType(String measureType) {
        this.measureType = measureType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.IOC_IMAGE
     *
     * @return the value of IFSAPP.SDIC_INDEX_DIMENSION.IOC_IMAGE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public String getIocImage() {
        return iocImage;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column IFSAPP.SDIC_INDEX_DIMENSION.IOC_IMAGE
     *
     * @param iocImage the value for IFSAPP.SDIC_INDEX_DIMENSION.IOC_IMAGE
     *
     * @abatorgenerated Fri Dec 16 14:04:38 CST 2016
     */
    public void setIocImage(String iocImage) {
        this.iocImage = iocImage;
    }

	public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}
}